# web server
nginx:
    image: nginx:latest
    ports:
        - "80:80"
        - "443:443"
    volumes:
        # app
        - ./www:/var/www/html
        # nginx configs
        - ./etc/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
        - ./etc/nginx/conf.d/:/etc/nginx/conf.d/:ro
    links:
        - fpm:__DOCKER_PHP_FPM__

# php-fpm
fpm:
    build: ./etc/php-fpm
    ports:
        - "9000"
    volumes:
        - ./www:/var/www/html
    links:
        - mysql:mysql

# database
mysql:
    image: mysql:latest
    ports:
        # Allow client to access 3306
        - "3306:3306"
    volumes:
        # NOTE: your data will be stored in ./mysql
        - ./etc/mysql:/var/lib/mysql
    env_file: .env