version: '3'
services:
  nginx:
    image: nginx:${NGINX_VERSION}
    container_name: nginx
    ports:
      - ${NGINX_HOST_HTTP_PORT}:80
      - ${NGINX_HOST_HTTPS_PORT}:433
    volumes:
      - ${APP_CODE_PATH_HOST}:/var/www/html
      - ./containers/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./logs/nginx:/var/log/nginx
    links:
      - php-fpm

  php-fpm:
    build: 
      context: ./containers/php
      args:
        - PHP_VERSION=${PHP_VERSION}
    container_name: php-fpm
    volumes: 
      - ./containers/php/php.ini:/usr/local/etc/php/php.ini
      - ${APP_CODE_PATH_HOST}:/var/www/html
    links:
      - mysql
      - maildev

  mysql:
    image: mysql:${MYSQL_VERSION}
    container_name: mysql
    ports:
      - ${MYSQL_PORT}:3306
    environment: 
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}

  maildev:
    image: djfarrelly/maildev
    container_name: maildev
    ports:
      - ${MAILDEV_HTTP_PORT}:80
      - ${MAILDEV_SMTP_PORT}:25
  